In [5]:
import numpy as np
np.random.random((3,3))

array([[0.3142488 , 0.12665992, 0.14244039],
       [0.91080333, 0.63667216, 0.9056621 ],
       [0.85272692, 0.6471072 , 0.79768316]])

In [26]:
#Task 1
#1 Declare a list of 1 to 4 using range()
a = list(range(1,5))
a

[1, 2, 3, 4]

In [23]:
#2 Continuing, create numpy array from this list, with dtype='float32'
anp = np.array((a), dtype='float32')
anp

array([1., 2., 3., 4.], dtype=float32)

In [25]:
#3 Create an numpy array of size 3 by 5 using np.zeros
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
#4 Create an numpy array of size 2 by 3 with filled value 1 / 3
np.full((2,3), 1/3)

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [31]:
#5 Create an array of 5 equal-distanced values for 0 to 10
np.linspace(0,10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
#6 Create an array of number for 0.001, 0.01, 0.1, 1 using np.logspace
np.logspace(-3, 0, 4)

array([0.001, 0.01 , 0.1  , 1.   ])

In [40]:
#7 Create a diagonal matrix of list [1, 2, 3, 4]
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [43]:
#8 Create a random array of size 4 by 5 all filled with random values between 0 and 1
np.random.random((4,5))

array([[0.47678082, 0.44993053, 0.52617213, 0.37814659, 0.49483001],
       [0.98790124, 0.43992333, 0.45710096, 0.58786983, 0.27243721],
       [0.51284967, 0.30463441, 0.12071505, 0.20885108, 0.95917584],
       [0.8964108 , 0.45423289, 0.50075756, 0.01417511, 0.05689448]])

In [45]:
#9 Create a random array of size 4 by 5 all filled with integer random values between 2 and 5
np.random.randint(2,5, (4,5))

array([[2, 4, 3, 3, 3],
       [3, 4, 2, 4, 2],
       [2, 4, 3, 4, 4],
       [3, 3, 4, 3, 3]])

In [47]:
#10 Create a random array of size 4 by 5 all filled with float random values between 2 and 5
np.random.uniform(low=2, high=5, size=(4,5))

array([[3.88814309, 2.53430375, 2.38600148, 3.69401266, 2.05304254],
       [2.58487635, 4.58679632, 2.30502403, 4.96812752, 3.12771289],
       [2.88559377, 3.89789997, 4.41964414, 4.69330854, 3.13313861],
       [2.5026406 , 2.99321823, 4.46480915, 4.44781004, 2.23353012]])

In [49]:
#11 Create a random array of size 4 by 5 with mean = 5, and std = 1 following a gaussian (normal) distribution
np.random.normal(5, 1, size=(4,5))

array([[6.3984574 , 4.8575929 , 4.87216136, 4.47924677, 3.30810399],
       [3.31598623, 4.7800458 , 3.77499121, 5.87302622, 4.08486424],
       [3.16339004, 4.22071057, 6.4517765 , 4.66197996, 6.7100493 ],
       [5.92119869, 5.04042974, 4.66962887, 5.79557407, 4.60475026]])

In [50]:
#12 Create an identity matrix of size 5 by 5
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
#Task 2
#1 Create a numpy array of size 3 by 4 with random float values between 1 to 5
np_array = np.random.uniform(low=1, high=5, size=(3,4))
print(np_array)

[[4.88517048 3.18116419 1.64494018 1.13005427]
 [4.22775986 3.43161972 2.92860484 1.50052379]
 [4.71123183 2.734404   2.62258613 1.26891053]]


In [84]:
#2 Continuing, print the shape of this array
np_array.shape

(3, 4)

In [85]:
#3 Continuing, access the first row of the array
np_array[0]

array([4.88517048, 3.18116419, 1.64494018, 1.13005427])

In [86]:
#4 Continuing, access the first column of the array
np_array[:,0]

array([4.88517048, 4.22775986, 4.71123183])

In [87]:
#5 Continuing, access the second row, and third column element
np_array[1,2]

2.9286048370015645

In [88]:
#6 Continuing, access the first two columns
np_array[:,:2]

array([[4.88517048, 3.18116419],
       [4.22775986, 3.43161972],
       [4.71123183, 2.734404  ]])

In [89]:
#7 Continuing, access the first and third columns using step
np_array[:,0::2]

array([[4.88517048, 1.64494018],
       [4.22775986, 2.92860484],
       [4.71123183, 2.62258613]])

In [90]:
#8 Continuing, print the whole matrix in reverse columns but not rows
np_array[:,::-1]

array([[1.13005427, 1.64494018, 3.18116419, 4.88517048],
       [1.50052379, 2.92860484, 3.43161972, 4.22775986],
       [1.26891053, 2.62258613, 2.734404  , 4.71123183]])

In [91]:
#9 Change the third row, fourth column element (i.e., the last element) to 999
np_array[2, 3] = 999
print(np_array)

[[  4.88517048   3.18116419   1.64494018   1.13005427]
 [  4.22775986   3.43161972   2.92860484   1.50052379]
 [  4.71123183   2.734404     2.62258613 999.        ]]


In [93]:
#Task 3
#1 Create a numpy array of size 200 by 4 with random float values between 1 to 5 and name it Data
Data = np.random.uniform(low=1, high=5, size=(200,4))
print(Data)

[[4.8925368  2.58306338 3.94200939 3.29766076]
 [2.58823155 2.68113723 1.69138145 3.37311958]
 [1.58721723 2.06838364 4.25311042 2.12144218]
 [4.28057305 4.68878899 3.3255107  2.06894676]
 [1.41365199 2.83624416 1.16514267 4.69057077]
 [3.75889194 3.47165038 4.49634403 2.75394793]
 [3.62583872 2.36432283 3.71158705 3.79798036]
 [2.92373071 2.36232313 4.55625027 2.70802855]
 [3.38646959 2.93835701 1.69844089 4.84287899]
 [2.53593492 4.98125169 2.28414648 4.14723821]
 [2.495524   3.45261955 4.80317887 2.90494947]
 [2.07268963 3.00220575 2.01104344 2.95087507]
 [3.23329724 2.79400811 4.07704091 4.06913366]
 [4.18920216 1.85361493 3.1638257  2.00220535]
 [4.93571906 3.09432102 2.50939022 2.80375697]
 [2.85932992 4.75444314 3.26823282 4.33231926]
 [4.00074705 1.64269197 3.43930281 2.07536201]
 [1.91869214 3.28821762 3.19207461 4.13373923]
 [1.58689822 1.29159224 2.16120201 2.39272547]
 [1.07712044 2.7824901  3.66507282 2.61737457]
 [1.74224844 1.36887676 2.75024669 4.27851442]
 [4.50659125 

In [103]:
#2 Split the array into two numpy arrays, X and y, where the X contains the first 3 columns and y contains the last column.
X = Data[:,0:3]
print(X.shape)
y = Data[:,3]
print(y.shape)

(200, 3)
(200,)


In [109]:
#3 Continuing, split the first 70% of the 200 rows of X and y and call them X_train and y_train. Similarly, populate X_test and y_test using same corresponding columns but 30\% rest of the data.
X_train = X[:140]
print(X_train.shape)
y_train = y[:140]
print(y_train.shape)
X_test = X[140:200]
print(X_test.shape)
y_test = y[140:200]
print(y_test.shape)

(140, 3)
(140,)
(60, 3)
(60,)


In [110]:
#1 Print the shape of the X_train and y_train. The first array should have shape (0.7 200, 3); the second array is (0.7 200, 1)
print(X_train.shape)
print(y_train.shape)

(140, 3)
(140,)


In [111]:
#2 Assign m = X_train.shape[0], and n = X_train.shape[1], where $m$ is number of samples, and $n$ is number of features
m = X_train.shape[0]
n = X_train.shape[1]
print(m, n)

140 3


In [128]:
#3 Randomly select one row of X_train by using np.random.randint to select the random row and called it X_i. Reshape it so that it has shape of (1, n)
random_index = np.random.randint(140)
print(random_index)
X_i = X_train[random_index]
print(X_i)
X_i = X_i.reshape(1,-1)
X_i.shape

117
[4.4340363  2.65099347 1.23804262]


(1, 3)

In [131]:
#4 Randomly select 50 contiguous rows from X_train by using np.random.randint to select a random starting row and called it mini_batch_X. If the index exceeds, simply grab whatever left.
random_index = np.random.randint(140)
mini_batch_x = X_train[random_index:random_index+50]
mini_batch_x
print(mini_batch_x.shape)

(50, 3)


In [140]:
#5 Write a for loop that breaks the X_train row-wise into 10 equal pieces without overlap, and simply print their shape
interval = X_train.shape[0]/10
for i in range(0, X_train.shape[0], int(interval)):
    batch = X_train[i:i+int(interval)]
    print(batch.shape)
    

(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)
(14, 3)


In [146]:
#6 Create an np.zero array called theta with shape of (n, )
theta = np.zeros(n,)
theta
theta.shape

(3,)

In [154]:
#7 Perform a dot product between X_train and theta and assign this value to a variable called yhat
yhat = np.dot(X_train, theta)

print(yhat.shape)

(140,)


In [158]:
#1 Create another variable called y with the same shape as yhat, and populate it with random values from 0 to 1.
y = np.random.uniform(0,1,(yhat.shape))
y.shape

(140,)

In [161]:
#2 Calculate the following $$ \frac{\sum\limits_{i=1}^{m} (y_i - \hat{y_i})^2}{m} $$
m = yhat.shape[0]
(((yhat-y)**2).sum())/m

0.3442370398914289

In [179]:
#Task 4
#1 From the above X_train from previous task, using concatenation, add a column of 1s along axis=1 and call it intercept

ones_ = np.ones((X_train.shape[0], 1))
intercept = np.concatenate((X_train, ones_), axis=1 )
intercept.shape


(140, 4)

In [183]:
#2 Create a theta of shape (n + 1, 4), with random values between 0 and 1
theta = np.random.uniform(0,1,(n+1,4))
theta.shape

(4, 4)

In [188]:
#3 Perform a dot product between X_train and theta, and assign this value to a variable called hot_encoded_yhat
hot_encoded_yhat = intercept @ theta
print(hot_encoded_yhat.shape)

(140, 4)


In [191]:
#4 Continuing, using broadcasting and vectorization, for each value (here I use example as value1) in hot_encoded_yhat, perform the following calculations.
hot_encoded_yhat = np.exp(hot_encoded_yhat)/np.sum(np.exp(hot_encoded_yhat))
hot_encoded_yhat[1]

array([0.00178571, 0.00178571, 0.00178571, 0.00178571])

In [192]:
#5 Create a variable called yhat which is equal to the np.argmax of hot_encoded_yhat along axis=1. That is, yhat has the shape of (X_train.shape[0], ). For example, if the first row of hot_encoded_yhat is [0.1, 0.2, 0.3, 0.4], since the fourth value is the biggest, the value will be its index which is 3.
yhat = np.argmax(hot_encoded_yhat, axis=1)
print(yhat.shape)
yhat

(140,)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [195]:
#6 Create a variable called y, containing shape of (X_train.shape[0], ) but with random int values from [0, 1, 2, 3]
y = np.random.randint(0,4,(X_train.shape[0], ))
y.shape

(140,)

In [216]:
#7 Assign a variable n_classses equal to the number of unique values in y
n_classes = len(np.unique(y))
n_classes

4

In [232]:
#Task 5 
#1 Take the above variables yhat and y, sum up the counts when their corresponding value are the same. Then divide this sum by $m$. Called this variable accuracy
print(yhat == y)
accuracy = ((yhat == y).sum())/m
print(accuracy)

[False  True False False False False  True False False  True False False
 False False False  True False False False False False False  True  True
 False False False False  True False False False False  True False False
  True False False False  True False False False False  True  True  True
 False False  True False False False False False False  True  True False
 False False False False False False  True False False False False False
  True False False False False False False False False False False False
 False False False False False  True False False False False False False
  True False False False  True  True False False False False  True False
 False  True False  True  True False  True False  True False False False
  True  True False False False  True False  True False False False False
 False  True False False False False False False]
0.2357142857142857


In [241]:
#2 Let's practice masking. Convert y into hot_encoded_y matrix of shape (X_train.shape[0], 4), where the column will be one according to its value, and other columns will be zero. For example, if the first row is 1, then it will become 0 1 0 0. If the second row is 2, then it will become 0 0 1 0
m = X_train.shape[0]
n = 4
hot_encoded_y = np.zeros((m,n))
print(hot_encoded_y)
for _class in range(n):
    cond = y == _class
    hot_encoded_y[np.where(cond), _class] = 1

hot_encoded_y[0]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0.

array([1., 0., 0., 0.])

In [ ]:
#3 Grab the data from data = np.genfromtxt('../data/perceptron.csv', delimiter=',', skip_header=1)
